# Generated by Django 2.2 on 2019-06-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fita', models.IntegerField(default=0)),
                ('posicao_x', models.CharField(max_length=200)),
                ('posicao_y', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaComponentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_componente', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('distancia_componentes', models.IntegerField(default=0)),
                ('angulo', models.IntegerField(default=0)),
                ('posicao_x_inicial', models.CharField(max_length=200)),
                ('posicao_y_inicial', models.CharField(max_length=200)),
                ('quantidade_componentes', models.IntegerField(default=0)),
                ('fita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidade_Central.Fita')),
            ],
        ),
    ]
