# Generated by Django 2.2 on 2019-06-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unidade_Central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiacomponentes',
            name='angulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='familiacomponentes',
            name='distancia_componentes',
            field=models.CharField(max_length=200),
        ),
    ]
